# Generated by Django 4.1.9 on 2023-06-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adresse',
            field=models.CharField(max_length=250, verbose_name='adresse'),
        ),
    ]
