# Generated by Django 4.1.9 on 2023-06-29 10:00

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_alter_userprofile_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('nom', models.CharField(max_length=200, null=True, verbose_name='nom')),
                ('prenom', models.CharField(max_length=200, null=True, verbose_name='prenom')),
                ('pays', models.CharField(max_length=100, null=True, verbose_name='pays')),
                ('ville', models.CharField(max_length=100, null=True, verbose_name='ville')),
                ('rue', models.CharField(max_length=200, null=True, verbose_name='rue')),
                ('code_postal', models.CharField(max_length=50, null=True, verbose_name='code_postal')),
                ('telephone', models.IntegerField(max_length=50, null=True, verbose_name='telephone')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cathegorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('photo', models.TextField(null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('username', models.CharField(max_length=250, verbose_name='username')),
                ('user_id', models.CharField(max_length=100, verbose_name='user_id')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('designation', models.CharField(max_length=100, verbose_name='designation')),
                ('prix', models.IntegerField(verbose_name='prix')),
                ('description', models.TextField(verbose_name='description')),
                ('photo_article', models.TextField(null=True, verbose_name='photo_article')),
                ('qte_en_stock', models.IntegerField(verbose_name='quantité en en stock')),
                ('cathegorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='amazon.cathegorie')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
