# Generated by Django 4.1.9 on 2023-06-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_adresse_cathegorie_user_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='telephone',
            field=models.IntegerField(null=True, verbose_name='telephone'),
        ),
    ]
